export interface IUser {
  profile: string,
  wantlist_url: string,
  rank: number,
  num_pending: number,
  id: number,
  num_for_sale: number,
  home_page: string,
  location: string,
  collection_folders_url: string,
  username: string,
  collection_fields_url: string,
  releases_contributed: number,
  registered: string,
  rating_avg: number,
  num_collection: number,
  releases_rated: number,
  num_lists: number,
  name: string,
  num_wantlist: number,
  inventory_url: string,
  uri: string,
  avatar_url: string,
  resource_url: string
}
